# (Optionnel) catch-all pour /api/*
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  
[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# API routes
[[redirects]]
  from = "/api/upload-image"
  to = "/.netlify/functions/upload-image"
  status = 200

[[redirects]]
  from = "/api/admin/list-products"
  to = "/.netlify/functions/admin-list-products"
  status = 200

[[redirects]]
  from = "/api/admin/save-products"
  to = "/.netlify/functions/admin-save-products"
  status = 200

[[redirects]]
  from = "/api/admin/delete-product"
  to = "/.netlify/functions/admin-delete-product"
  status = 200

[build.environment]
  NODE_VERSION = "20"
